### ISSUE TITLE
EmployerUsers Search Endpoint and ApiClient

### ISSUE THREAD

**Issue by sachpatel** [SkillsFundingAgency/das-employerusers#57]
The API client has the following code:

```
public async Task<PagedApiResponseViewModel<UserSummaryViewModel>> SearchEmployerUsers(string criteria, int pageNumber = 1, int pageSize = 1000)
{
    return await GetResource<PagedApiResponseViewModel<UserSummaryViewModel>>($"/api/users/search/{criteria}?pageNumber={pageNumber}&pageSize={pageSize}");
}
```

The criteria parameter cannot be a string with '@' or '.' symbols and so the endpoint does not perform a search for users when an email address is passed as the criteria. Maybe the criteria can be apassed to the API action as a query string parameter and also from the API client.

The [dbo].[SearchUsers] stored procedure does allow for searching by email.

**Comment by dashton82** [comment]
We allow @ in the url's for MYA, can you url encode the values being sent instead of doing this change?

**Comment by sachpatel** [comment]
The issue is when sending email addresses with '.' characters. e.g. Mark.gwilliam@valtech.co.uk

When this is placed within the url before the querystring I'm not sure the parameter is routed to the action correctly. The '.' characters in this part of the url are most likely looking for a different handler.
